### ISSUE TITLE
Build containers created using the "kratix add containers" command

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-cli#36]
**As** Penny
**I want** containers that I created using "kratix add containers" command to be built when i build my promise
**So that** I can create my whole promise in the CLI, speeding up the promise build process

---

We have seen users create their own tools to build pipeline containers so that they can quickly iterate the building of their promise. This is great! We can try to make the promise-building experience better by including the ability to build the containers from within the CLI so they aren't reliant on providing external scripts. 

### UX
**kratix build container LIFECYCLE/ACTION/PIPELINE-NAME --image CONTAINER-IMAGE [all the other bits you need to provide]**
**kratix build container --all [all the other bits you need to provide]**
  traverse the current directory structure and build all docker files you find in there that match the LIFECYCLE/ACTION/PIPELINE-NAME hierarchy
 
**kratix build container [blah] --push**
  Pushes the built container so that a kaf of the promise would apply with the shiny new container

 **Todos**

- [x] Implementation
- [ ] Docs

**Comment by kirederik** [comment]
Users flow:


```
> kratix add container resource/configure/mypipeline --image kratix-workshop/app-pipeline-image:v1.0.0
> kratix add container resource/configure/mypipeline --image kratix-workshop/app-pipeline-image:v1.0.0 --name second-container
...

> tree
.
├── README.md
├── dependencies
│   └── dependencies.yaml
├── example-resource.yaml
├── promise.yaml
└── workflows
    └── resource
        └── configure
            └── mypipeline
                └── kratix-workshop-app-pipeline-image
                    ├── Dockerfile
                    ├── resources
                    └── scripts
                        └── pipeline.sh

> kratix build container --help

Usage:
  kratix build container LIFECYCLE/ACTION/PIPELINE-NAME [flags]

Examples:
  # Build a 


Flags:


```
