### ISSUE TITLE
feat: add cli releases

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix-cli#40]
There's currently no way to consume the Kratix CLI other than cloning and compiling the binary yourself.

Let's improve this by automatically creating releases of the CLI, so the users can download the compiled binary for their OS directly from Github.

We can use [release-please](https://github.com/googleapis/release-please) with [go-releaser](https://goreleaser.com/) to make the entire process very simple.

**Comment by aclevername** [comment]
# Go Releaser investigation

Looking at go-releaser it acts upon the creation of a git tag, it doesn't create the tag for you. It will:
- create the binaries (multi arch)
- create a github release at the tag
- upload the binaries to the release
- add auto-generated release notes from commit history (can be customised) to the github release
- [set an go ldflag for the version](https://goreleaser.com/cookbooks/using-main.version/) when building the binary so we can support `kratix-cli --version` without having to edit the code 

We can use [github actions](https://github.com/goreleaser/goreleaser-action) workflow that already exists, or write it by hand in circleci (former is probably easier).

# Release-please investigation
Looking at [release-please](https://github.com/googleapis/release-please) it autogenerates a PR that is the placeholder of the next release. The PR contains release notes, and the PR is continually updated as new commits get pushed, [example](https://github.com/syntasso/kratix-cli/pull/42). The PR is created via github workflow. the release note generation is a bit more clever than go-releaser, it uses [convention commit](https://www.conventionalcommits.org/en/v1.0.0/) to filter out whats a feature by commits prefixed with `feat:`, and bug fixes from `fix:`. When you merge the PR (which just updates the `CHANGELOG` file) it:
- Creates a tag
- Create a github release from the tag, adds the release notes

image stolen from https://danwakeem.medium.com/improve-your-github-releases-10x-with-this-one-simple-action-56e59e46dd85
![image](https://github.com/user-attachments/assets/45862e86-c75c-477b-a96c-13d62f763747)

Release-please **does not doing anything related to building code**. They [recommend you have other tooling that gets triggered on Github releases being created](https://github.com/googleapis/release-please/issues/1415#issuecomment-1118942757) be responsible for uploading artifacts to the release. [Rip grep](https://github.com/BurntSushi/ripgrep/blob/71d71d2d98964653cdfcfa315802f518664759d7/.github/workflows/release.yml#L277) is an example of a CI using Release-please that has a github action to trigger on a release being created, and then manually uploads the binaries.

# Questions

- Does goreleaser and release-please play well together?
  - it seems yes! [Not much documentation](https://www.google.com/search?q=%22goreleaser%22+%22release-please%22&oq=%22g&gs_lcrp=EgZjaHJvbWUqBggCEEUYOzIGCAAQRRg5MgYIARBFGDsyBggCEEUYOzIGCAMQRRhAMhMIBBAuGIMBGMcBGLEDGNEDGIAEMg0IBRAAGIMBGLEDGIAEMg0IBhAAGIMBGLEDGIAEMg0IBxAAGIMBGLEDGIAE0gEIMzI4M2owajeoAgCwAgA&sourceid=chrome&ie=UTF-8), but a big project as an example to copy is [k8sgpt cli](https://github.com/k8sgpt-ai/k8sgpt/blob/main/.github/workflows/release.yaml). They use release-please to handle release notes and manual releases, and then delegate to goreleaser to upload the artifacts.
- are auto-generated release notes good enough?
   - we could do a manual release process with manual release notes if we wanted.
- do we want automatic or manual releases?
  - if automatic, we can use the Kratix approach and do a release on every green run of `main` by pushing a new tag at the end of CI (if using goreleaser). Unclear how to do automatic releases with release-please, and tbh it seems against the point of it
  - if manual, we can manually push tags (if using goreleaser) or manually merge release-please PR (if using release-please)
 
 # Proposal
 We use go release to release, and follow the Kratix convention of pushing a new tag on every green run of main.

**Comment by aclevername** [comment]
after chatting with @catmo-syntasso @kirederik we're going to try out the 2nd approach of using release-please combined with gorelaser. Two reasons:
- its different release process to Kratix, we might learn we love/hate it/something in-between 
- since its an early product we might be doing lots of small commits to kratix cli for bug fixes, non-code changes etc, which made make the releases quite noisy. Doing manual releases lets us batch up

**Comment by aclevername** [comment]
draft PR open, next steps in development documented in the PR
